services:

  frontend:
    image: tharunrajravi/skyalert-frontend:latest
    container_name: skyalert-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: tharunrajravi/skyalert-backend:latest
    container_name: skyalert-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    restart: unless-stopped

  worker:
    image: tharunrajravi/skyalert-backend:latest
    container_name: skyalert-worker
    command: python worker.py
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - backend
    restart: unless-stopped
