services:

  frontend:
    image: tharunrajravi/skyalert-frontend:latest
    container_name: skyalert-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: tharunrajravi/skyalert-backend:latest
    container_name: skyalert-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - skyalert_data:/app/data   # ⭐ DATABASE LIVES HERE
    restart: unless-stopped

  worker:
    image: tharunrajravi/skyalert-backend:latest
    container_name: skyalert-worker
    command: python worker.py
    env_file:
      - .env
    volumes:
      - skyalert_data:/app/data   # ⭐ SAME DATABASE SHARED
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  skyalert_data:
